projeto-rjm/index.html, projeto-rjm/src/data/services/API.jsx, projeto-rjm/src/data/services/Session.jsx, projeto-rjm/src/pages/AddProj.jsx, projeto-rjm/src/pages/Login.jsx, projeto-rjm/src/pages/RecSenha.jsx, projeto-rjm/src/pages/Registro.jsx, projeto-rjm/src/pages/Usuarios.jsx
Correção e adequação no cadastro, agora o cadastro está armazenando adequadamente os dados; alterações em login para o retorno do token, agora o **login é feito através do e-mail** e não do nome; e a **adição do Token na variável de sessão**, com **chave: authToken** e **valor do próprio**.
=> fix(API): Corrigem interações com a API.

projeto-rjm/src/data/services/API.jsx, projeto-rjm/src/index.jsx, projeto-rjm/src/pages/AddProj.jsx, projeto-rjm/src/pages/App.jsx, projeto-rjm/src/pages/EsqueciSenha.jsx, projeto-rjm/src/pages/Login.jsx, projeto-rjm/src/pages/Principal.jsx, projeto-rjm/src/pages/RecSenha.jsx, projeto-rjm/src/pages/RedefinirSenha.jsx, projeto-rjm/src/pages/Registro.jsx, projeto-rjm/src/pages/Usuarios.jsx, projeto-rjm/src/pages/routes.jsx
Altera a o arquivo RecSenha para EsqueciSenha, adiciona o arquivo RedefinirSenha e conserta algumas alterações de endpoint.
closes #53
=> feat(pages): Adiciona a página Redefinir senha.

projeto-rjm/src/data/services/API.jsx, projeto-rjm/src/pages/AddProj.jsx, projeto-rjm/src/pages/App.jsx, projeto-rjm/src/pages/Login.jsx, projeto-rjm/src/pages/Projetos.jsx, projeto-rjm/src/pages/Usuarios.jsx, projeto-rjm/src/pages/routes.jsx
Altera os nomes dos arquivos, para a melhor adaptação à função, e adiciona novas páginas.
=> feat(api): Implementa ao site novas páginas.

projeto-rjm/src/pages/Editar_Projetos.jsx, projeto-rjm/src/pages/Projetos.jsx, projeto-rjm/src/pages/routes.jsx, projeto-rjm/src/ui/styles/Projetos/Projetos.css
Alteração no estilo da página para 'adequação' com o design feito pela UI/UX e adição da página editar projetos, ainda precisa ser feita.
=> style(): Estilo página Projetos.

projeto-rjm/src/data/services/API.jsx, projeto-rjm/src/pages/Add_Projetos.jsx, projeto-rjm/src/pages/Editar_Projeto.jsx, projeto-rjm/src/pages/Esqueci_Senha.jsx, projeto-rjm/src/pages/Registro.jsx, projeto-rjm/src/pages/Sprints.jsx, projeto-rjm/src/pages/routes.jsx, projeto-rjm/src/pages/util/functions.jsx, projeto-rjm/src/ui/components/_cabecalho.jsx
Formulário de edição de projeto, ainda necessário rota da API, e ajuste dos botões de retorno das páginas.
=> feat(): Implementação de forms em Editar_Projeto.

projeto-rjm/src/data/services/API.jsx, projeto-rjm/src/ui/components/_cabecalho.jsx, projeto-rjm/src/ui/styles/cabProjeto.module.css
Alteração no css para que o navegador identifique a classe.
=> fix(): Alterações no estilo Cabeçalho.

projeto-rjm/src/data/services/API.jsx, projeto-rjm/src/data/services/Session.jsx, projeto-rjm/src/pages/Login.jsx, projeto-rjm/src/pages/Perfil.jsx, projeto-rjm/src/pages/Usuarios.jsx, projeto-rjm/src/pages/util/functions.jsx
Faz a verificação das páginas Login, Perfil e Usuarios. Alteração na função de logout, para limpar todos as variáveis.
=> feat(): Verificações de páginas.

projeto-rjm/src/pages/App.jsx, projeto-rjm/src/ui/icons/fundoAppQuemSomos.svg, projeto-rjm/src/ui/styles/App/App.module.css
Muda o css da página principal para a melhor adaptação do projeto.
=> Style(app): Muda o estilo em APP.

projeto-rjm/src/data/services/API.jsx, projeto-rjm/src/pages/Add_Projetos.jsx, projeto-rjm/src/pages/Add_Sprints.jsx, projeto-rjm/src/pages/Editar_Usuario.jsx, projeto-rjm/src/pages/Perfil.jsx
Correção de erros em add_Sprints, add_Projetos, Perfil e Editar_Usuario; Erros estes que foram parcialmente resolvidos; Perfil necessita de alterações no front e Editar_Usuario não deixa mudar as informações nos campos inputs.
=> fix(): Correção de alguns erros.

projeto-rjm/src/data/services/API.jsx, projeto-rjm/src/pages/App.jsx
Foi adicionada uma função na pagina inicial que muda o texto do botão dependendo se o usuário esta logado ou não
=> styles(): Alteração no botão de criar conta da App.jsx

projeto-rjm/src/data/services/API.jsx
Adiciona uma nova função, addUserEquipe, no qual adicina o usuário à uma equipe especifica. Agora quando se cria uma nova equipe, o usuário criador recebe o papel dev de default.
=> fix(): Altera o adicionar equipes.

projeto-rjm/src/data/services/API.jsx, projeto-rjm/src/pages/Add_Sprints.jsx, projeto-rjm/src/pages/Editar_Sprint.jsx, projeto-rjm/src/pages/Equipes.jsx, projeto-rjm/src/pages/Projetos.jsx, projeto-rjm/src/pages/Sprints.jsx, projeto-rjm/src/pages/routes.jsx, projeto-rjm/src/pages/util/functions.jsx, projeto-rjm/src/ui/components/_cabecalho.jsx
Cria o arquivo Editar_Sprint, não há código, adiciona rota para tal função. Altera Sprint.jsx fazendo com que receba as sprints do back. Alguns comentários nos arquivos.
=> feat(): Integra a rota da API - Sprints.

projeto-rjm/src/pages/Add_Equipes.jsx, projeto-rjm/src/pages/Add_Projetos.jsx, projeto-rjm/src/pages/Editar_Usuario.jsx, projeto-rjm/src/pages/Projetos.jsx, projeto-rjm/src/ui/styles/App/App.module.css, projeto-rjm/src/ui/styles/Projetos/Projetos.module.css, projeto-rjm/src/ui/styles/Quem_Somos/Quem_Somos.module.css, projeto-rjm/src/ui/styles/Shared/AddEditProjUsuario.module.css, projeto-rjm/src/ui/styles/Shared/FormConta.module.css, projeto-rjm/src/ui/styles/principal.css
Modifica a cor de fundo da página principal, adiciona modificações no fundo da página quem somos e altera o tamanho da fonte e a centralização em addEditProjUsuario
=> style(): Altera estilo em adicionar equipes e projetos e editar usuário.

projeto-rjm/src/data/services/API.jsx, projeto-rjm/src/pages/util/functions.jsx
Corrige erro com o botão de voltar do cabeçalho, que agora funciona igual o do navegador.
=> styles(): Mudança no botão de voltar do cabeçalho

projeto-rjm/src/pages/Projetos.jsx, projeto-rjm/src/ui/components/_cabecalho.jsx, projeto-rjm/src/ui/styles/cabProjeto.module.css
Adiciona na página projetos o botão que dá acesso à página de criação de projetos. No cabeçalho foi adicionado um botão que leva o usuário para a página de equipes, tornando a navegação do site mais intuitiva.
=> feat(): Adiciona o botão de criar projetos e de ver Equipes.

projeto-rjm/src/pages/Add_Projeto.jsx, projeto-rjm/src/pages/Projetos.jsx, projeto-rjm/src/ui/styles/Projetos/Projetos.module.css, projeto-rjm/src/ui/styles/Shared/AddEditProjUsuario.module.css
Projetos.jsx:a div botaoNewProjeto agora abre uma janela modal
=> style():a div botaoNewProjeto agora abre uma janela modal

projeto-rjm/src/pages/Projetos.jsx, projeto-rjm/src/ui/styles/Projetos/Projetos.module.css
style():  
1. projetos.jsx e projetos.module.css: o design da pagina foi mais aproximado do design presente no figma
=> style():projetos.jsx

projeto-rjm/src/data/services/API.jsx, projeto-rjm/src/pages/Add_Equipe.jsx, projeto-rjm/src/pages/Equipes.jsx, projeto-rjm/src/pages/Projetos.jsx, projeto-rjm/src/pages/routes.jsx
Adiciona a janela modal no botão para adicionar equipe e apaga a rota da função add_equipe.
=> feat(): Adiciona janela modal.

projeto-rjm/src/pages/Equipes.jsx, projeto-rjm/src/ui/styles/Equipes/Equipes.module.css, projeto-rjm/src/ui/styles/Projetos/Projetos.module.css
equipes.jsx:o botao roxo agora fica em cima dos cartoes com as equipes;o botao roxo agora tambem muda de tamanho e de cursor quando o usuario coloca o mouse em cima dele
projetos.module.css:.botaoNewProjeto agora muda de tamanho quando o usuario coloca seu mouse em cima dele
=> style():equipes.jsx e projetos.module.css

projeto-rjm/src/data/services/API.jsx, projeto-rjm/src/pages/Add_Task.jsx, projeto-rjm/src/pages/Editar_Equipe.jsx, projeto-rjm/src/pages/Editar_Projeto.jsx, projeto-rjm/src/pages/Editar_Task.jsx, projeto-rjm/src/pages/routes.jsx
Corrige o formulário de adição, que agora adiciona task, porém o editar não está recebendo as informações como o esperado, deve ser analisado.
=> feat(Task): formulário de adição

projeto-rjm/src/data/services/API.jsx, projeto-rjm/src/pages/Add_Projeto.jsx, projeto-rjm/src/pages/Projetos.jsx, projeto-rjm/src/ui/styles/Shared/AddEditProjUsuario.module.css
Reverts SilasReuel/tcc_frontend#157
=> Revert "Revert "style():mudança em como funciona o botao de fechar modal""

projeto-rjm/src/data/services/API.jsx, projeto-rjm/src/ui/styles/Shared/AddEditProjUsuario.module.css, projeto-rjm/src/ui/styles/Shared/FormConta.module.css
style():  
-AddEditProjUsuario.module.css e FormConta.module.css: os botões presentes nas duas pagina agora mudam de cor quando o usuário coloca o mouse em cima deles
=> style():animacoes em alguns botoes do site

projeto-rjm/src/pages/Projetos.jsx, projeto-rjm/src/pages/Sprints.jsx, projeto-rjm/src/pages/Tasks.jsx, projeto-rjm/src/ui/styles/Projetos/Projetos.module.css, projeto-rjm/src/ui/styles/Tasks/Tasks.module.css
Altera o código e CSS de 'Tasks.jsx' para se adequar ao design. Adiciona um título nas páginas de _Projetos_ e _Sprints_, além de algumas alterações no CSS.
=> styles(): Mudanças na página de tasks e nos títulos de outras páginas

projeto-rjm/src/data/services/API.jsx, projeto-rjm/src/pages/Add_Projeto.jsx
-Add_Projeto.jsx:o usuário não pode mais criar um projeto para outra equipe quando ele está na aba de outra. Ao criar um projeto, ele agora é automatica inserido na equipe em que o usuário está atualmente
=> fix():mudança na parte de adicionar projeto

projeto-rjm/src/pages/Editar_Equipe.jsx, projeto-rjm/src/ui/styles/Shared/AddEditProjUsuario.module.css, projeto-rjm/src/ui/styles/Tasks/Tasks.module.css
-Editar_Equipe.jsx e AddEditProjUsuario.module.css:melhorias no design e correção da falta de texto branco; 
-Tasks.module.css:foi adicionado um design mobile
=> style():correções no design

projeto-rjm/src/ui/styles/Equipes/Equipes.module.css, projeto-rjm/src/ui/styles/Projetos/Projetos.module.css, projeto-rjm/src/ui/styles/Sprints/Sprints.module.css, projeto-rjm/src/ui/styles/Tasks/Tasks.module.css, projeto-rjm/src/ui/styles/task/task.module.css
Foi corrigido erros na responsividade do site todo, principalmente na altura da página que gerava erros e em descrições que vazavam das divs ou as expandiam. Também foram padronizadas as cores usadas nas divs de conteúdo de todas as páginas que as apresentam.
=> fix(): Corrigidos diversos erros no CSS

projeto-rjm/src/pages/App.jsx, projeto-rjm/src/ui/styles/task/task.module.css
Foram feitos alguns ajustes no css de Task.jsx, além de uma leve mudança em App.jsx
=> style(): ajustes em task

projeto-rjm/package-lock.json, projeto-rjm/src/data/services/API.jsx, projeto-rjm/src/pages/App.jsx, projeto-rjm/src/pages/Editar_Projeto.jsx, projeto-rjm/src/pages/Editar_Sprint.jsx, projeto-rjm/src/pages/Editar_Task.jsx, projeto-rjm/src/pages/Redefinir_Senha.jsx, projeto-rjm/src/pages/Sprints.jsx, projeto-rjm/src/pages/Tasks.jsx, projeto-rjm/src/ui/styles/App/App.module.css, projeto-rjm/src/ui/styles/Shared/AddEditProjUsuario.module.css, projeto-rjm/src/ui/styles/Shared/FormConta.module.css, projeto-rjm/src/ui/styles/Sprints/Sprints.module.css, projeto-rjm/src/ui/styles/Tasks/Tasks.module.css
-Editar_Projeto.jsx: adição de um botão para cancelar a edição;
-Editar_Sprint.jsx e Editar_Task.jsx: correção de como o botão "cancelar" retorna à página anterior. Também foi adicionado um código para caso o usuário não tenha página anterior no histórico, que irá fechar a página;
-Redefinir_Senha.jsx e FormConta.module.css: Agora a imagem que fica na esquerda preenche todo o espaço vertical;
-Sprints.jsx, Sprints.module.css, Tasks.jsx e Tasks.module.css: o botão de adicionar uma nova sprint ou tasks agora é animado. O nome da classe do botão em cada página também foi alterado para algo mais apropriado para o contexto da página.
-App.jsx: a imagem no fundo agora cobre toda a página.
=> style(): correções no design css

projeto-rjm/src/data/services/API.jsx, projeto-rjm/src/ui/styles/cabProjeto.module.css
- _cabecalho.jsx: mudanças de como o cabeçalho é renderizado quando a tela é muito pequena.
=> style(): melhorias no design mobile do cabeçalho

projeto-rjm/src/data/services/API.jsx, projeto-rjm/src/pages/Add_Equipe.jsx, projeto-rjm/src/pages/Add_Projeto.jsx, projeto-rjm/src/pages/Add_Sprint.jsx, projeto-rjm/src/pages/App.jsx, projeto-rjm/src/pages/Editar_Equipe.jsx, projeto-rjm/src/pages/Editar_Perfil.jsx, projeto-rjm/src/pages/Editar_Sprint.jsx, projeto-rjm/src/pages/Quem_Somos.jsx
Altera o formulário de adição e remoção de usuário da equipe; concerta certos erros de importação.
=> feat(): adiciona a operação de editar membros da equipe

projeto-rjm/src/data/services/API.jsx, projeto-rjm/src/pages/Equipes.jsx, projeto-rjm/src/pages/Projetos.jsx, projeto-rjm/src/ui/styles/Equipes/Equipes.module.css, projeto-rjm/src/ui/styles/Projetos/Projetos.module.css
Faz a exclusão de equipes e projetos, não testado totalmente por conta do servidor desatualizado.
=> feat(): Adiciona a exclusão de equipes e projetos.

projeto-rjm/src/data/services/API.jsx, projeto-rjm/src/pages/Editar_Equipe.jsx, projeto-rjm/src/pages/Equipes.jsx, projeto-rjm/src/ui/styles/Equipes/Equipes.module.css, projeto-rjm/src/ui/styles/Shared/AddEditProjUsuario.module.css
O botão excluir agora está em editar, porém não funciona.
=> fix(): alteração do local do botão.

projeto-rjm/src/data/services/API.jsx, projeto-rjm/src/pages/Projetos.jsx, projeto-rjm/src/ui/styles/App/App.module.css, projeto-rjm/src/ui/styles/Projetos/Projetos.module.css
-API.jsx: adição de um comentário com o link da API do servidor do CTI, para facilitar o desenvolvimento de páginas que requerem o uso de uma API;
-Projetos.jsx e Projetos.module.css: adição de espaçamento na navbar, para melhorar a visualização;
-App.module.css: quando a tela estava muito pequena, o botão "ver equipes"/"criar conta" era cortado pela sua div, agora a div cresce junto com o botão, para melhorar a visualização da página em telas no formato mobile/retrato.
=> style(): correções em app.jsx e na navbar
